sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jauH4Gd86V+i8b6X4VErZnzCdHgWMhCPLNvbwcluFHWaw13RHKOT/56BIbacanxitNEagr9/mRODBER8jg2LC+hbeAHaDWkIaUHuYEAFyMgsufbgu7bXy54gPDrceC7YH2FiQp/CsOM7JLpnXbJVYSNvp34NWIzkmM3Pzyd5gQ24EONUtuzI6VCMHG8+Zs1EZBuX9KdE79qx622AZljxhEB8//mhOMMcF0QgGOHXgz1vYNFDHksQ5Wh0EPa38x5YHAS4GDpWVO8WIMjffsvcc+r1Xf93+0ZaxOQ1owXL77t6RH0kl5uFbEjHI3ti7BpLitiynJkjR2Q0Ng/URhtUNRCbZBgnYHJuFehHo2S9Na775kZYZme/Vgaie6/yLhAYO7iQczC8sTgzrGmQbEGw9fINZJiC7k/yQY33DPTSUDqAPQH73krQWpMPhJiFAUa7xhZgl/x/FJXxhHqxTIJ7+wcBeLCQGFfzzHGqyeWcLxSZe0/eD0Ehd9Q3RjKZ1Gz2gcr5P72MHNHDfZLHiqPTwD+aYqIZW3QzkXGn4AAMspbc4zgDnX/kN4ArUIXD0hj9O05a3C/A+ftcZ6mKJX5lIvQSvkfmodYta5JfddpSu6OTQIkrp+xnQvLW/gC0viBVGzKM16Pozu7o1UgNzWef5o+soW6imY32nI2i46/4KxA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/An-Unprotected-Female-at-the-Pyramids_3710
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy